//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiTudo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class buses
    {
        public int idBus { get; set; }
        public Nullable<int> capacidad { get; set; }
        public Nullable<int> year { get; set; }
        public string color { get; set; }
        public string estado { get; set; }
    }
}
